#!/usr/bin/env bash
#
# The single entry point on a fresh CachyOS install (minimal profile, no
# desktop). Run as the normal user — it calls sudo itself for the steps that
# need it:
#
#     curl -fsSL https://raw.githubusercontent.com/nicolasmaclean/dotfiles/main/ansible/bootstrap.sh | bash
#
# or, from an existing checkout, just `ansible/bootstrap.sh`. Extra arguments
# are passed through to ansible-playbook, so a first run on a machine that
# already has a desktop should be:
#
#     ansible/bootstrap.sh --check --diff
#
# The clone is HTTPS on purpose. A fresh box has no SSH key, and the key is
# generated by the `identity` role near the end of the run — so the remote is
# switched to SSH afterwards, breaking the chicken-and-egg.
set -euo pipefail

REPO_HTTPS="https://github.com/nicolasmaclean/dotfiles.git"
REPO_SSH="git@github.com:nicolasmaclean/dotfiles.git"
DOTFILES="${DOTFILES:-$HOME/dotfiles}"

# `ansible`, not `ansible-core`: the full package is what ships
# community.general and community.crypto, which is where pacman:, ini_file:,
# npm: and openssh_keypair: come from. requirements.yml pins them anyway, and
# is genuinely load-bearing for kewlfft.aur, which is bundled with nothing.
#
# base-devel and paru are prerequisites of the `aur` role rather than things it
# installs: paru is what builds, base-devel is what it builds with. The CachyOS
# ISO ships paru already, so --needed usually makes both a no-op — which is
# also why this needs no guard. --needed is the --noconfirm-safe idempotent
# form; without it pacman reinstalls on every run.
sudo pacman -Sy --needed --noconfirm ansible git base-devel paru

if [ -d "$DOTFILES/.git" ]; then
    echo "==> $DOTFILES exists, updating"
    git -C "$DOTFILES" pull --ff-only
else
    echo "==> cloning into $DOTFILES"
    git clone "$REPO_HTTPS" "$DOTFILES"
fi

# ansible.cfg is only read from the current directory, so this cd is what makes
# the inventory path and transport=local take effect.
cd "$DOTFILES/ansible"

ansible-galaxy collection install -r requirements.yml

# Every host in the inventory is local, so a run that is not limited to this
# machine would apply the other machine's host_vars to it. Fail before the
# playbook rather than provision the wrong box.
HOST="$(hostname)"
if ! ansible-inventory --host "$HOST" >/dev/null 2>&1; then
    echo "hostname '$HOST' is not in inventory/hosts.yml." >&2
    echo "Add it there and write inventory/host_vars/$HOST.yml first." >&2
    exit 1
fi

ansible-playbook site.yml --limit "$HOST" --ask-become-pass "$@"

cat <<NEXT

==> done. Two manual steps remain, both once per host:
      1. add the SSH key printed above to GitHub, then
           git -C "$DOTFILES" remote set-url origin $REPO_SSH
      2. Spotify: register the app, write
         ~/.config/qtile-spotify/credentials.json (0600), and run
           python3 ~/.config/qtile/spotify_auth.py
NEXT
